configVersion: 2.0
  ## This should be placed in the plugin directory
  ## for more help configuring see the wiki
  ## https://github.com/alkarinv/BattleArena/wiki
  ## Change this file to customize your event

  MovecraftArena:  ### This should be exactly the same as the name you registered
    enabled: true
    database: SuperCrusher # needs BattleTracker
    rated: true # if database is enabled
    prefix: "&6[MovecraftArena]&e"
    cmd: movecraftarena
    nTeams: 2+
    teamSize: 1
    joinType: Queue ## there are 2 join types, Queue and JoinPhase
    victoryCondition: LastManStanding
    ### You can delete any stages/transitions that have no options
    ### for a list of options see wiki
    preReqs: ## Prerequisites for joining
      options: []
    onEnter:
      options: [storeAll]
    onLeave:
      options: [restoreAll]
    onJoin:  ## when they join the match
      options: []
    onPreStart: ## x seconds before onStart
      options: []
    onStart: ## Starting
      options: [teleportIn, pvpOn]
    onSpawn: ## what happens when a player spawns
      options: [hunger=20, health=20]
      giveClass:
        default: Gladiator
    onDeath: ## what happens when a player dies
      options: []
    onComplete: ## what happens when things end
      options: [teleportOut, clearInventory]
    winner: ## what to give the winner
      options: [health=20, hunger=20]
    losers: ## what to give the losers
      options: []